# Generated by Django 6.0.4 on 2026-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
