# Generated by Django 6.0.4 on 2026-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_album_options_alter_galleryimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(verbose_name='когда сделанны фотки'),
        ),
    ]
