# Generated by Django 6.0.4 on 2026-04-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Фото для главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото на главной',
                'verbose_name_plural': 'Фото на главной',
            },
        ),
    ]
