# Generated by Django 6.0.4 on 2026-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Пакеты', 'verbose_name_plural': 'Пакеты'},
        ),
    ]
