# Generated by Django 6.0.4 on 2026-04-23 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_minutes',
            field=models.CharField(default=datetime.datetime(2026, 4, 23, 18, 35, 37, 366633, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Длительность в минутах'),
            preserve_default=False,
        ),
    ]
