# Generated by Django 6.0.4 on 2026-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='booking.extraservice'),
        ),
    ]
