# Generated by Django 6.0.4 on 2026-04-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_extra_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='bookingtype',
            options={'verbose_name': 'Тип бронирования', 'verbose_name_plural': 'Типы бронирования'},
        ),
        migrations.AlterModelOptions(
            name='extraservice',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Дополнительные услуги', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
    ]
