# Generated by Django 6.0.4 on 2026-04-23 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options_alter_bookingtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtype',
            name='duration_minutes',
            field=models.CharField(default=datetime.datetime(2026, 4, 23, 17, 42, 55, 867161, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='Длительность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookingtype',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
