# Generated by Django 6.0.4 on 2026-04-23 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingtype_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.bookingtype'),
        ),
    ]
