# Generated by Django 6.0.4 on 2026-04-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_package_name_alter_booking_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20),
        ),
    ]
