# Generated by Django 6.0.4 on 2026-04-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_status'),
        ('services', '0004_alter_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='package_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.package', verbose_name='Выбранный пакет'),
        ),
    ]
