# Generated by Django 6.0.4 on 2026-04-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_package_name_booking_selected_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.bookingtype', verbose_name='Тип бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Почта клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='booking.extraservice', verbose_name='Доп услуги'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Сумма заказа'),
        ),
    ]
